name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Install V lang
        run: |
          git clone https://github.com/vlang/v && cd v && make && ./v symlink && cd ..
      - name: Install pubtools dependecncies
        run: v install patrickpissurno.redis && v install despiegk.crystallib && v install nedpals.vex 
      -name: Build pubtools
        run: git clone https://github.com/crystaluniverse/publishtools && cd publishtools/publishtools && v -cc gcc -gc boehm -cflags -static -d net_blocking_sockets -d static_boehm publishtools.v
      -name: Run publishtools
        run: ./publishtools
      - run: echo "🍏 This job's status is ${{ job.status }}."
